server:
  port: 5000
  servlet:
    context-path: /wander
    session:
      cookie:
        path: /wander
#  ssl:
#    key-store-password: 123456@KEy
#    key-store: 'classpath:mykeystore.p12'
#    key-store-type: PKCS12
#    key-alias: wander
  error:
    whitelabel:
      enabled: false


spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:./data/user
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

logging:
  level:
    org.springframework.security: DEBUG